# coding=utf-8

comment_ru = {

    'Converting products of sine or cosine to a sum of sine or cosine terms': u'',
    'Intermediate solution': u'',
    'Isolating sin(p)**2 + cos(p)**2': u'',
    'It\'s handy to use an identity for product of sine and cosine': u'',
    'Multiply both sides of equation by:': u'',
    'Reducing using Pythagorean identity': u'',
    'Reversing the substitution': u'',
    'Separating sums in sine or cosine terms': u'',
    'Since we have a product of sine and cosine with same arguments': u'',
    'Using Pythagorean identity': u'',
    'Using an identity for product of sine and cosine, we get:': u'',
    'Using decrease cosine power identity': u'',
    'Using decrease sine power identity': u'',
    'Using identity for cosine of double angle': u'',
    'Using identity for sine of double angle': u'',
    'Using reverse formula for cosine of double argument, we get': u'',
    'Using reverse half-angle identity for cosine': u'',
    'Using the substitution': u'',

    'Add {} row multiplied by {} to {} row ': u'Добавим {} ряд, умноженный на {} к {} ряду ',
    'Add {} row to {} row': u'Добавим {} ряд к {} ряду',
    'Add the second equation multiplied by {} to the first equation': u'Добавим второе уравнение, умноженное на {} к первому уравнению',
    'After substituting the value in the equation we get that it is not a root': u'После подстановки этого числа в уравнения, убеждаемся, что оно не является корнем',
    'All rows have removed. Therefore every choice of variable values is a solution': u'Все строки были элиминированы, следовательно любое значение переменной является решением',
    'And we have a restriction': u'Также имеем следующее ограничение',
    'And we have restrictions': u'Также имеем следующее ограничения',
    'Any number is a solution to this equation': u'Любое число является решением данного уравнения',
    'Approximate': u'Примерно',
    'At first solve the coressponding homogeneous equation': u'Сначала решим соответствующее однородное уравнение',
    'At first, solve the corresponding homogeneous equation': u'Сначала решим соответствующее однородное уравнение',
    'Consider the function': u'Рассмотрим функцию',
    'Consider the root': u'Рассмотрим корень',
    'Consider the solution': u'Рассмотрим решение',
    'Converting back to a system of equations': u'Перейдём обратно к системе уравнений',
    'Divide this equation by {}': u'Разделим числитель и знаменатель на {}',
    'Dividing the numerator and denominator by ': u'Разделим числитель и знаменатель на ',
    'Evaluate the integral': u'Вычислим интеграл',
    'Evaluate the limit': u'Вычислим предел',
    'Evaluate the limits of the numerator and the denominator': u'Вычислим пределы числителя и знаменателя',
    'Evaluate these limits': u'Вычислим эти пределы',
    'Every root of this equation is a root of the following equation': u'Все корни этого уравнения являются также корнями следующего уравнения',
    'Finally the given equation write as': u'Окончательно заданное уравнение запишем в виде',
    'Finally we get': u'В итоге,',
    'Finally we have !!!': u'В итоге получаем',
    'Finally we have the following roots': u'Окончательно получаем следующие корни',
    'Finally we have the following solution set': u'Окончательно получаем следующее множество решений',
    'Finally we have': u'В итоге получаем',
    'Finally, ': u'В итоге, ',
    'Finally, we get': u'В итоге получаем',
    'Finally, we have': u'В итоге получаем',
    'Finally, we obtain': u'В итоге получаем',
    'Find V': u'Найдем V',
    'Find a particular solution in the form': u'Будем искать частное решение в виде',
    'Find the derivative': u'Найдём производную',
    'Find the inverse substitution': u'Найдём обратную подстановку',
    'Find the particular solution in the form': u'Найдём частное решение в виде',
    'Find the roots of the denominator': u'Найдём корни знаменателя',
    'Find the roots of the the equation': u'Найдём корни уравнения',
    'Find the solution in the form': u'Найдём решение в виде',
    'Find the subintegral': u'Найдём интеграл',
    'Hence the system has no solution': u'Следовательно, система не имеет решений',
    'Hence we get the following solution': u'Таким образом, получили следующее решение',
    'Introduce a new variable {}': u'Введём новую переменную {}',
    "Let's": "Пусть",
    'Move the constant outside the derivative sign': u'Вынесем константу из-под знака производной',
    'Move the constant outside the integral sign': u'Вынесем константу из-под знака интеграла',
    'Multiply {} row by {}': u'Умножим {} строку на {}',
    'Otherwise': u'Иначе',
    'Putting parts together we get': u'Собирая всё вместе',
    'Raise both sides of the equation to the {} power': u'Возведём обе части уравнения в {} степень',
    'Raise the both sides of the equation to the power': u'Возведём обе части уравнения в степень',
    'Remove zeros rows': u'Уберём нулевые строки',
    'Rewrite it as': u'Перепишем уравнение',
    'Rewrite the equation': 'Перепишем уравнение',
    'Rewrite the equation as': u'Перепишем уравнение',
    'Rewrite the equation as a sum of two terms': u'Перепишем уравнение в виде суммы двух выражений',
    'Rewrite the equation in the form': u'Перепишем уравнение в виде',
    'Rewrite the function': u'Перепишем функцию',
    'Rewrite the inequalities as': u'Перепишем неравенство как',
    'Rewrite the integrand': u'Перепишем подыинтегральное выражение',
    'Rewrite the second term as': u'Второе выражение запишем в виде',
    'Rewrite the system as': u'Перепишем систему как',
    'Rewrite this equation as': u'Перепишем это уравнение в виде',
    'Rewrite this equations as': u'Перепишем это уравнение в виде',
    'Rewrite this limit as': u'Перепишем предел в виде',
    'Simplify': u'Упростим',
    'Since the equation {} = 0 is not be satisfied, the system is inconsistent.': u'Так как уравнение = 0 не может быть удовлетворено, то система не совместна',
    'Since the polynomial is constant, there are no roots': u'Так как многочлен является константой, то корней нет',
    'Since': u'Так как',
    'Solve it using the method of undetermined coefficients': u'Решим, используя метод неопределённых коэффициентов',
    'Solve it using the method of variation of parameters': u'Решим, используя метод вариации постоянной',
    'Solve the equation': u'Решим уравнение',
    'Solve the first equation': u'Решим первое уравнение',
    'Solve the inequality': u'Решим неравенство',
    'Solve the second equation': u'Решим второе уравнение',
    'Solve the system of equation': u'Решим систему уравнений',
    'Solve the system of equations': u'Решим систему уравнений',
    'Solve the system': u'Решим систему',
    'Square the both sides of the inequality to eliminate the radical sign': u'Возведём в квадрат обе части неравенства, для того чтобы избавится от знака корня',
    'Substitute every root to the system': u'Подставим каждый корень в уравнение',
    'Subtract {} row from {} row': u'Вычтем {} строку из {} строки',
    'Subtract {} row multiplied by {} from {} row': u'Вычтем {} строку, умноженную на {} из {} строки',
    'Swap {} row and {} row': u'Поменяем местами {} строку и {} строку',
    'Test all rational numbers in the form p/q': u'Проверим все рациональные числа в виде p/q',
    'Test the point': u'Проверим точку',
    'The base of log is greater than 1 therefore we have': u'Основание логарифма больше 1, следовательно,',
    'The base of log is less than 1 therefore we have': u'Основание логарифма меньше 1, следовательно,',
    'The characteristic equation is': u'Характеристическое уравнение имеет вид',
    'The chracteristic equation is': u'Характеристическое уравнение имеет вид',
    'The derivative of the function ': u'Производная функции ',
    'The equation can be rewritten as': u'Уравнение может быть переписано в виде',
    'The first root is': u'Первый корень равен',
    'The following derivative has been found above': u'Следующая производная была вычислена выше',
    'The function is a derivative therefore the integral is': u'Функция является производной, следовательно, интеграл равен',
    'The function is a polinomial therefore the antiderivative is': u'Функкция является мночленом, следовательно, интеграл равен',
    'The function is a quotient of two polynomials': u'Функция является отношением двух многочленов',
    'The function is a sum therefore the integral is equal to the sum of the integrals of the summands': u'Функция является суммой, а производная суммы равна сумме производных',
    'The function is a sum; the derivative of the sum is the sum of the derivatives of the summands.': u'Функция является суммой, а интеграл суммы равен сумме интегралов',
    'The function is constant therefore the derivative is 0': u'Функция постоянна, следовательно, производная равна 0',
    'The function is constant therefore the integral is': u'Функция постоянна, следовательно интеграл равен',
    'The function is equal 0 therefore the integral of this function is 0': u'Функция равна тожествено нулю, следовательно, интеграл равен 0',
    'The have the following solution set': u'Получаем следующее множество решений,',
    'The integral of this function can be found in the integral table and is equal to': u'Интеграл от этой функции может быть найден в таблице производных и равен',
    'The integrand has repeated itself, so we have': u'Подынтегральное выражение повторилось, поэтому',
    'The limit is': u'Предел равен',
    'The polynomial is constant. Therefore there is no root.': u'Многочлен является константой, следовательно корней нет',
    'The polynomial is cyclotomic': u'Многочлен является циклотомическим',
    'The result is': u'Результат',
    'The root of the equation is zero': u'Корень этого уравнения равен нулю.',
    'The root of this equation is': u'Корень этого уравнения',
    'The roots are': u'Корни равны',
    'The roots of the characteristic equation are': u'Корни характеристического уравнения равны',
    'The roots of the quadric equation can be found using formulas': u'Корни крадратного уравнения могут быть найдены по формулам',
    'The roots of the quartic equation is': u'Корни уравнения четвёртой степени могут быть найдены по формулам"',
    'The roots of this equation are equal to zero': u'Корни этого уравнения равны 0',
    'The solution has the form': u'Решение имеет вид',
    'The solution of this equation is': u'Решение этого уравнения равно',
    'The solution to this equation is the union of the solutions of the following equations': u'Решение этого уравнения является объединением решений следующий уравнений',
    'The solution to this equation is': u'Решением \nэтого \nуравнения \nявляется',
    'The solution to this ineqality is': u'Решение неравества имеет вид',
    'The system has no solution': u'Система не имеет решенийfire',
    'The way of evaluating of the integral is unknown': u'Интеграл не может быть вычислен',
    'There is no solution because the values of sqrt are non-negative': u'Решений нет, так как значение корня неотрицательно',
    'There is no solution': u'Решений нет',
    'Therefore the derivative of the sum is': u'Следовательно, производная суммы равна',
    'Therefore the integral of the sum is': u'Следовательно, интеграл суммы равен',
    'Therefore the other roots are': u'Следовательно, другими корнями будут',
    'Therefore the quartic equation can be rewritten as': u'Следовательно, квадратное уравнение может быть переписано в виде',
    'Therefore the roots are': u'Следовательно, корни равны',
    'Therefore the roots of cubic equations are': u'Следовательно, корни кубического уравнения равны',
    'Therefore the roots of quartic equation are': u'Следовательно, корни уравнения равны',
    'Therefore the roots of the bi-quadratic equation are': u'Следовательно, корни биквадратного уравнения равны',
    'Therefore the roots of the characteristic equation are': u'Следовательно, корни характеристического уравнения равны',
    'Therefore the roots of the cubic equation are': u'Следовательно корни кубического уравнения равны',
    'Therefore the roots of the cubic equation is': u'Следовательно, корни кубического уравнения равны',
    'Therefore the roots of this quadratic equation are': u'Следовательно, корни квадратного уравнения равны',
    'Therefore the solution is': u'Следовательно, решение имеет вид',
    'Therefore there is no root': u'Следовательно, корней нет',
    'Therefore there is no solution': u'Следовательно, решений нет',
    'Therefore we get': u'Следовательно, мы получаем',
    'Therefore we have ': u'Поэтому имеем ',
    'Therefore we have the following intervals to test': u'Поэтому необходимо проверить следующие интервалы',
    'Therefore we have the following solutions of the system': u'Поэтому получаем следующие решения системы',
    'Therefore we have': u'Следовательно мы получаем',
    'Therefore': u'Следовательно',
    'Therefore, we obtain': u'Следовательно мы получаем',
    'This derivative can be found in the derivative table and is equal to': u'Производная может быть найдена в таблице производных и равна',
    'This derivative has been found above': u'Производная вычислена выше',
    'This derivative is equal to 1': u'Производная равна 1',
    'This equation cannot be solved': u'Уравнение не может быть решено',
    'This equation cannot be solved': u'Уравнение не может быть решено',
    'This equation is a 1st order exact ordinary differential equation': u'Уравнения является уравнением первого порядка',
    'This equation is a 2nd order Liouville differential equation': u'Уравнение является уравнением Лиувилля',
    'This equation is a Bernoulli differential equation': u'Уравнения является уравнением Бернулли',
    'This equation is a Riccati differential equation': u'Уравнение является уравнением Риккарти',
    'This equation is a differential equation with linear coefficients': u'Уравнения является дифференциальным уравнением с постоянными коэффициентами',
    'This equation is a homogeneous Euler differential equation': u'Уравнение яляется однородным уравнением Эйлера',
    'This equation is bi-quadratic': u'Уравнение является биквадратным',
    'This equation is linear': u'Уравнение является линейным',
    'This equation is quartic': u'Уравнение является квадратным',
    'This inequality is trigonometric': u'Это неравенство является тригонометрическим',
    'This integral is definite': u'Интеграл является определённым',
    'This is 1st order linear differential equation': u'Это линейное уравнение первого порядка',
    'This is a linear differential equation with constant coefficients': u'Это линейное уравнение с постоянными коэффициентами',
    'This is a linear equation': u'Это линейное уравнение',
    'This is a linear homogeneous differential equation with constant coefficients': u'Это линейное однородное уравнение с постоянными коэффициентами',
    'This is a separable 1st order differential equation': u'Это уравнение первого порядка с разделяющимися переменными',
    'This is a system of polynomial equations': u'Эта система является системой полиномиальных уравнений',
    'This limit is equal to': u'Предел равен',
    'This step is correct if': u'Этот шаг верен, если ',
    'This system has no solution': u'Эта система не имеет решений',
    'Thus the interval': u'Следовательно, интервал',
    'Thus we have the following solution set': u'Следовательно, мы имеем следующее множество решений',
    'To solve this equation we find roots of the following equations': u'Для того чтобы решить это уравнение нужно найти корни следующих уравнений',
    "Use Cardano's method": "Воспользуемся методом Кордано",
    'Use Descartes-Euler method': u'Воспользуемся методом Эйлера',
    'Use Ferrari method': u'Воспользуемся методом Феррари',
    'Use numerical methods': u'Воспользуемся численными методами',
    'Use the Gauss method': u'Применим метод Гаусса',
    'Use the back substitution': u'Сделаем обратную замену',
    'Use the chain rule': u'Используем правило дифференцирования сложной функции',
    'Use the critical points method': u'Используем метод интервалов',
    'Use the following substitution': u'Применим следующую подстановку',
    'Use the formula': u'Воспользуемся формулой',
    'Use the formulas': u'Воспользуемся формулами',
    'Use the invert substitution we get': u'Используя обратную подстановку, получим',
    'Use the method of integration by parts': u'Используем метод интегрирования по частям',
    'Use the rational root test': u'Проверим некоторые рациональные числа',
    'Use the substitution': u'Используем подстановку',
    'Using addition rule, we obtain': u'Используя правило суммы, получим',
    'Using formula for the sum of two cosines we get': u'Применим формулу суммы косинусов',
    'Using formula for the sum of two sines we get': u'Применим формулу суммы синусов',
    'Using multiplication rule, we obtain': u'Используя правило произведения, получим',
    'Using the formula for the sine of the sum we get': u'Используя формулу синуса суммы, получим',
    'Using the fundamental theorem of calculus, we get that the value of the definite integral is': u'Используя формулу Ньютона-Лейбница, получаем, что значение определённого интеграла равно',
    'Using the invert substitution we have': u'Используя обратную подстановку получаем',
    'Using the tangent half-angle substitution we get': u'Выразим тригонометрические функции через тангенс половинного угла',
    'We have the following resolvent equation': u'Получаем следующую резольвенту',
    'We have the following roots of the quartic equation': u'Имеем следующие корни',
    'We have the following roots': u'Имеем следующие корни',
    'We have the following solution': u'Получаем следующее решение',
    'We have the following solutions': u'Получаем следующее решения',
    'We have the following system': u'Имеем следующую систему',
    'We have': u'Имеем',
    'We know that ': u'Известно, что ',
    'We know that': u'Известно, что',
    'Where z1 and z2 are the roots of equation': u'Где z1 и z2 -- корни уравнения',
    'can be found in the derivative table and is equal to': u'может быть найдена в таблице производных и равна',
    'is a part of the solution set': u'является частью множества решений',
    'is not a part of the solution set': u'не является частью множества решений',
    'the system is equivalent to the following systems': u'система эквивалентна следующим системам',
    'where {} can be any integer': u'где {} может быть любым целым числом',
    'where R is a root of the resolvent equation': u'где R является корнем следующей резольвенты',
    'where p is a divisor of {} and q is a divisor of {}': u'где p это делитель {} и q - это делитель {}',
    'where': u'где',
    'Convert this system into an augmented matrix': u'Преобразуем систему уравнений в матрицу',
    'Find inadmissible values': u'Найдем недопустимые значения',
    'Find the values when the following expression is undefined': u'Найдем значения, когда следующее выражение неопределено',
    'Rewrite equation': u'Перепишем выражение',
    'Solve the equation': u'Решим выражение',
    'Solve the following two equations': u'Решим следующие выражения',
    'Solve the system of equations': u'Решим систему уравнений',
    'The discriminant is': u'Дискриминантом является',
    'The following values are inadmissible': u'Следующие значения недопустимы',
    'The intersection of the general solution': u'Пересечение общих решений',
    'The solution ': u'Решение ',
    'The value {} is a root': u'Значение {} является корнем',
    'The value {} is an extraneous root': u'Значение {} является посторонним корнем',
    'The value {} is not a root because it is a root of the denominator': u'Значение {} не является корнем, так как обращает знаменатель в 0',
    'There are no real roots': u'Нет действительных корней',
    'Therefore the equation has no solution': u'Поэтому уравнение не имеет решения',
    'Therefore the solution is': u'Поэтому решение',
    'Therefore the solutions are equal to': u'Поэтому решения равны',
    'Therefore this is not a solution': u'Поэтому это не является решением',
    'This equation is cubic': u'Уравнение является кубическим',
    'This equation is linear': u'Уравнение является линейным',
    'This equation is quadratic': u'Уравнение является квадратным',
    'This system is a system of linear equations': u'Система является системой линейных уравнений',
    'Use the substitution': u'Воспользуемся подстановкой',
    'We get': u'Получим',
    'We have': u'Имеем',
    'and the set of inadmissible values': u'и множество недопустимых решений',
    'and': u'и',
    'assuming that': u'предполагая, что',
    'is a subset of the solution': u'является подмножеством множества решений',
    'is not emtpy': u'не пусто',

    # other localizable strings
    'welcome string': u'Напишите любую формулу...',
    'purchase button': 'gfx/ru_show-solutions.png',
}

def solution_comment_table_ru():
    return comment_ru


