comment_en = {
    'Add {} row multiplied by {} to {} row ': 'Add {} row multiplied by {} to {} row ',
    'Add {} row to {} row': 'Add {} row to {} row',
    'Add the second equation multiplied by {} to the first equation': 'Add the second equation multiplied by {} to the first equation',
    'After substituting the value in the equation we get that it is not a root': 'After substituting the value in the equation we get that it is not a root',
    'All rows have removed. Therefore every choice of variable values is a solution': 'All rows have removed. Therefore every choice of variable values is a solution',
    'And we have a restriction': 'And we have a restriction',
    'And we have restrictions': 'And we have restrictions',
    'Any number is a solution to this equation': 'Any number is a solution to this equation',
    'Approximate': 'Approximate',
    'At first solve the coressponding homogeneous equation': 'At first solve the coressponding homogeneous equation',
    'At first, solve the corresponding homogeneous equation': 'At first, solve the corresponding homogeneous equation',
    'Consider the function': 'Consider the function',
    'Consider the root': 'Consider the root',
    'Consider the solution': 'Consider the solution',
    'Converting back to a system of equations': 'Converting back to a system of equations',
    'Divide this equation by {}': 'Divide this equation by {}',
    'Dividing the numerator and denominator by ': 'Dividing the numerator and denominator by ',
    'Evaluate the integral': 'Evaluate the integral',
    'Evaluate the limit': 'Evaluate the limit',
    'Evaluate the limits of the numerator and the denominator': 'Evaluate the limits of the numerator and the denominator',
    'Evaluate these limits': 'Evaluate these limits',
    'Every root of this equation is a root of the following equation': 'Every root of this equation is a root of the following equation',
    'Finally the given equation write as': 'Finally the given equation write as',
    'Finally we get': 'Finally we get',
    'Finally we have !!!': 'Finally we have !!!',
    'Finally we have the following roots': 'Finally we have the following roots',
    'Finally we have the following solution set': 'Finally we have the following solution set',
    'Finally we have': 'Finally we have',
    'Finally, ': 'Finally, ',
    'Finally, we get': 'Finally, we get',
    'Finally, we have': 'Finally, we have',
    'Finally, we obtain': 'Finally, we obtain',
    'Find V': 'Find V',
    'Find a particular solution in the form': 'Find a particular solution in the form',
    'Find the derivative': 'Find the derivative',
    'Find the inverse substitution': 'Find the inverse substitution',
    'Find the particular solution in the form': 'Find the particular solution in the form',
    'Find the roots of the denominator': 'Find the roots of the denominator',
    'Find the roots of the the equation': 'Find the roots of the the equation',
    'Find the solution in the form': 'Find the solution in the form',
    'Find the subintegral': 'Find the subintegral',
    'Hence the system has no solution': 'Hence the system has no solution',
    'Hence we get the following solution': 'Hence we get the following solution',
    'Introduce a new variable {}': 'Introduce a new variable {}',
    "Let's": "Let's",
    'Move the constant outside the derivative sign': 'Move the constant outside the derivative sign',
    'Move the constant outside the integral sign': 'Move the constant outside the integral sign',
    'Multiply {} row by {}': 'Multiply {} row by {}',
    'Otherwise': 'Otherwise',
    'Putting parts together we get': 'Putting parts together we get',
    'Raise both sides of the equation to the {} power': 'Raise both sides of the equation to the {} power',
    'Raise the both sides of the equation to the power': 'Raise the both sides of the equation to the power',
    'Remove zeros rows': 'Remove zeros rows',
    'Rewrite it as': 'Rewrite it as',
    'Rewrite the equation': 'Rewrite the equation',
    'Rewrite the equation as': 'Rewrite the equation as',
    'Rewrite the equation as a sum of two terms': 'Rewrite the equation as a sum of two terms',
    'Rewrite the equation in the form': 'Rewrite the equation in the form',
    'Rewrite the function': 'Rewrite the function',
    'Rewrite the inequalities as': 'Rewrite the inequalities as',
    'Rewrite the integrand': 'Rewrite the integrand',
    'Rewrite the second term as': 'Rewrite the second term as',
    'Rewrite the system as': 'Rewrite the system as',
    'Rewrite this equation as': 'Rewrite this equation as',
    'Rewrite this equations as': 'Rewrite this equations as',
    'Rewrite this limit as': 'Rewrite this limit as',
    'Simplify': 'Simplify',
    'Since the equation {} = 0 is not be satisfied, the system is inconsistent.': 'Since the equation {} = 0 is not be satisfied, the system is inconsistent.',
    'Since the polynomial is constant, there are no roots': 'Since the polynomial is constant, there are no roots',
    'Since': 'Since',
    'Solve it using the method of undetermined coefficients': 'Solve it using the method of undetermined coefficients',
    'Solve it using the method of variation of parameters': 'Solve it using the method of variation of parameters',
    'Solve the equation': 'Solve the equation',
    'Solve the first equation': 'Solve the first equation',
    'Solve the inequality': 'Solve the inequality',
    'Solve the second equation': 'Solve the second equation',
    'Solve the system of equation': 'Solve the system of equation',
    'Solve the system of equations': 'Solve the system of equations',
    'Solve the system': 'Solve the system',
    'Square the both sides of the inequality to eliminate the radical sign': 'Square the both sides of the inequality to eliminate the radical sign',
    'Substitute every root to the system': 'Substitute every root to the system',
    'Subtract {} row from {} row': 'Subtract {} row from {} row',
    'Subtract {} row multiplied by {} from {} row': 'Subtract {} row multiplied by {} from {} row',
    'Swap {} row and {} row': 'Swap {} row and {} row',
    'Test all rational numbers in the form p/q': 'Test all rational numbers in the form p/q',
    'Test the point': 'Test the point',
    'The base of log is greater than 1 therefore we have': 'The base of log is greater than 1 therefore we have',
    'The base of log is less than 1 therefore we have': 'The base of log is less than 1 therefore we have',
    'The characteristic equation is': 'The characteristic equation is',
    'The chracteristic equation is': 'The chracteristic equation is',
    'The derivative of the function ': 'The derivative of the function ',
    'The equation can be rewritten as': 'The equation can be rewritten as',
    'The first root is': 'The first root is',
    'The following derivative has been found above': 'The following derivative has been found above',
    'The function is a derivative therefore the integral is': 'The function is a derivative therefore the integral is',
    'The function is a polinomial therefore the antiderivative is': 'The function is a polinomial therefore the antiderivative is',
    'The function is a quotient of two polynomials': 'The function is a quotient of two polynomials',
    'The function is a sum therefore the integral is equal to the sum of the integrals of the summands': 'The function is a sum therefore the integral is equal to the sum of the integrals of the summands',
    'The function is a sum; the derivative of the sum is the sum of the derivatives of the summands.': 'The function is a sum; the derivative of the sum is the sum of the derivatives of the summands.',
    'The function is constant therefore the derivative is 0': 'The function is constant therefore the derivative is 0',
    'The function is constant therefore the integral is': 'The function is constant therefore the integral is',
    'The function is equal 0 therefore the integral of this function is 0': 'The function is equal 0 therefore the integral of this function is 0',
    'The have the following solution set': 'The have the following solution set',
    'The integral of this function can be found in the integral table and is equal to': 'The integral of this function can be found in the integral table and is equal to',
    'The integrand has repeated itself, so we have': 'The integrand has repeated itself, so we have',
    'The limit is': 'The limit is',
    'The polynomial is constant. Therefore there is no root.': 'The polynomial is constant. Therefore there is no root.',
    'The polynomial is cyclotomic': 'The polynomial is cyclotomic',
    'The result is': 'The result is',
    'The root of the equation is zero': 'The root of the equation is zero',
    'The root of this equation is': 'The root of this equation is',
    'The roots are': 'The roots are',
    'The roots of the characteristic equation are': 'The roots of the characteristic equation are',
    'The roots of the quadric equation can be found using formulas': 'The roots of the quadric equation can be found using formulas',
    'The roots of the quartic equation is': 'The roots of the quartic equation is',
    'The roots of this equation are equal to zero': 'The roots of this equation are equal to zero',
    'The solution has the form': 'The solution has the form',
    'The solution of this equation is': 'The solution of this equation is',
    'The solution to this equation is the union of the solutions of the following equations': 'The solution to this equation is the union of the solutions of the following equations',
    'The solution to this equation is': 'The solution to this equation is',
    'The solution to this ineqality is': 'The solution to this ineqality is',
    'The system has no solution': 'The system has no solution',
    'The way of evaluating of the integral is unknown': 'The way of evaluating of the integral is unknown',
    'There is no solution because the values of sqrt are non-negative': 'There is no solution because the values of sqrt are non-negative',
    'There is no solution': 'There is no solution',
    'Therefore the derivative of the sum is': 'Therefore the derivative of the sum is',
    'Therefore the integral of the sum is': 'Therefore the integral of the sum is',
    'Therefore the other roots are': 'Therefore the other roots are',
    'Therefore the quartic equation can be rewritten as': 'Therefore the quartic equation can be rewritten as',
    'Therefore the roots are': 'Therefore the roots are',
    'Therefore the roots of cubic equations are': 'Therefore the roots of cubic equations are',
    'Therefore the roots of quartic equation are': 'Therefore the roots of quartic equation are',
    'Therefore the roots of the bi-quadratic equation are': 'Therefore the roots of the bi-quadratic equation are',
    'Therefore the roots of the characteristic equation are': 'Therefore the roots of the characteristic equation are',
    'Therefore the roots of the cubic equation are': 'Therefore the roots of the cubic equation are',
    'Therefore the roots of the cubic equation is': 'Therefore the roots of the cubic equation is',
    'Therefore the roots of this quadratic equation are': 'Therefore the roots of this quadratic equation are',
    'Therefore the solution is': 'Therefore the solution is',
    'Therefore there is no root': 'Therefore there is no root',
    'Therefore there is no solution': 'Therefore there is no solution',
    'Therefore we get': 'Therefore we get',
    'Therefore we have ': 'Therefore we have ',
    'Therefore we have the following intervals to test': 'Therefore we have the following intervals to test',
    'Therefore we have the following solutions of the system': 'Therefore we have the following solutions of the system',
    'Therefore we have': 'Therefore we have',
    'Therefore': 'Therefore',
    'Therefore, we obtain': 'Therefore, we obtain',
    'This derivative can be found in the derivative table and is equal to': 'This derivative can be found in the derivative table and is equal to',
    'This derivative has been found above': 'This derivative has been found above',
    'This derivative is equal to 1': 'This derivative is equal to 1',
    'This equation cannot be solved': 'This equation cannot be solved',
    'This equation cannot be solved': 'This equation cannot be solved',
    'This equation is a 1st order exact ordinary differential equation': 'This equation is a 1st order exact ordinary differential equation',
    'This equation is a 2nd order Liouville differential equation': 'This equation is a 2nd order Liouville differential equation',
    'This equation is a Bernoulli differential equation': 'This equation is a Bernoulli differential equation',
    'This equation is a Riccati differential equation': 'This equation is a Riccati differential equation',
    'This equation is a differential equation with linear coefficients': 'This equation is a differential equation with linear coefficients',
    'This equation is a homogeneous Euler differential equation': 'This equation is a homogeneous Euler differential equation',
    'This equation is bi-quadratic': 'This equation is bi-quadratic',
    'This equation is linear': 'This equation is linear',
    'This equation is quartic': 'This equation is quartic',
    'This inequality is trigonometric': 'This inequality is trigonometric',
    'This integral is definite': 'This integral is definite',
    'This is 1st order linear differential equation': 'This is 1st order linear differential equation',
    'This is a linear differential equation with constant coefficients': 'This is a linear differential equation with constant coefficients',
    'This is a linear equation': 'This is a linear equation',
    'This is a linear homogeneous differential equation with constant coefficients': 'This is a linear homogeneous differential equation with constant coefficients',
    'This is a separable 1st order differential equation': 'This is a separable 1st order differential equation',
    'This is a system of polynomial equations': 'This is a system of polynomial equations',
    'This limit is equal to': 'This limit is equal to',
    'This step is correct if': 'This step is correct if',
    'This system has no solution': 'This system has no solution',
    'Thus the interval': 'Thus the interval',
    'Thus we have the following solution set': 'Thus we have the following solution set',
    'To solve this equation we find roots of the following equations': 'To solve this equation we find roots of the following equations',
    "Use Cardano's method": "Use Cardano's method",
    'Use Descartes-Euler method': 'Use Descartes-Euler method',
    'Use Ferrari method': 'Use Ferrari method',
    'Use numerical methods': 'Use numerical methods',
    'Use the Gauss method': 'Use the Gauss method',
    'Use the back substitution': 'Use the back substitution',
    'Use the chain rule': 'Use the chain rule',
    'Use the critical points method': 'Use the critical points method',
    'Use the following substitution': 'Use the following substitution',
    'Use the formula': 'Use the formula',
    'Use the formulas': 'Use the formulas',
    'Use the invert substitution we get': 'Use the invert substitution we get',
    'Use the method of integration by parts': 'Use the method of integration by parts',
    'Use the rational root test': 'Use the rational root test',
    'Use the substitution': 'Use the substitution',
    'Using addition rule, we obtain': 'Using addition rule, we obtain',
    'Using formula for the sum of two cosines we get': 'Using formula for the sum of two cosines we get',
    'Using formula for the sum of two sines we get': 'Using formula for the sum of two sines we get',
    'Using multiplication rule, we obtain': 'Using multiplication rule, we obtain',
    'Using the formula for the sine of the sum we get': 'Using the formula for the sine of the sum we get',
    'Using the fundamental theorem of calculus, we get that the value of the definite integral is': 'Using the fundamental theorem of calculus, we get that the value of the definite integral is',
    'Using the invert substitution we have': 'Using the invert substitution we have',
    'Using the tangent half-angle substitution we get': 'Using the tangent half-angle substitution we get',
    'We have the following resolvent equation': 'We have the following resolvent equation',
    'We have the following roots of the quartic equation': 'We have the following roots of the quartic equation',
    'We have the following roots': 'We have the following roots',
    'We have the following solution': 'We have the following solution',
    'We have the following solutions': 'We have the following solutions',
    'We have the following system': 'We have the following system',
    'We have': 'We have',
    'We know that ': 'We know that ',
    'We know that': 'We know that',
    'Where z1 and z2 are the roots of equation': 'Where z1 and z2 are the roots of equation',
    'can be found in the derivative table and is equal to': 'can be found in the derivative table and is equal to',
    'is a part of the solution set': 'is a part of the solution set',
    'is not a part of the solution set': 'is not a part of the solution set',
    'the system is equivalent to the following systems': 'the system is equivalent to the following systems',
    'where {} can be any integer': 'where {} can be any integer',
    'where R is a root of the resolvent equation': 'where R is a root of the resolvent equation',
    'where p is a divisor of {} and q is a divisor of {}': 'where p is a divisor of {} and q is a divisor of {}',
    'where': 'where',
    'Convert this system into an augmented matrix': 'Convert this system into an augmented matrix',
    'Find inadmissible values': 'Find inadmissible values',
    'Find the values when the following expression is undefined': 'Find the values when the following expression is undefined',
    'Rewrite equation': 'Rewrite equation',
    'Solve the equation': 'Solve the equation',
    'Solve the following two equations': 'Solve the following two equations',
    'Solve the system of equations': 'Solve the system of equations',
    'The discriminant is': 'The discriminant is',
    'The following values are inadmissible': 'The following values are inadmissible',
    'The intersection of the general solution': 'The intersection of the general solution',
    'The solution ': 'The solution ',
    'The value {} is a root': 'The value {} is a root',
    'The value {} is an extraneous root': 'The value {} is an extraneous root',
    'The value {} is not a root because it is a root of the denominator': 'The value {} is not a root because it is a root of the denominator',
    'There are no real roots': 'There are no real roots',
    'Therefore the equation has no solution': 'Therefore the equation has no solution',
    'Therefore the solution is': 'Therefore the solution is',
    'Therefore the solutions are equal to': 'Therefore the solutions are equal to',
    'Therefore this is not a solution': 'Therefore this is not a solution',
    'This equation is cubic': 'This equation is cubic',
    'This equation is linear': 'This equation is linear',
    'This equation is quadratic': 'This equation is quadratic',
    'This system is a system of linear equations': 'This system is a system of linear equations',
    'Use the substitution': 'Use the substitution',
    'We get': 'We get',
    'We have': 'We have',
    'and the set of inadmissible values': 'and the set of inadmissible values',
    'and': 'and',
    'assuming that': 'assuming that',
    'is a subset of the solution': 'is a subset of the solution',
    'is not emtpy': 'is not emtpy',

    # other localizable strings
    'welcome string': 'Write any formula...',
    'purchase button': 'gfx/en_show-solutions.png',
}

def solution_comment_table_en():
    return comment_en

